### ISSUE TITLE
Thank you for the hard work :)

### ISSUE THREAD

**Issue by adamg261** [sam210723/xrit-rx#20]
HI Sam

Just wanted to let you know I have been able to follow your instructions for raspberry and have a working setup ( minus the signal lol )

(side note)
python3 tools\keymsg-decrypt.py EncryptionKeyMessage_001F2904C905.bin 001F2904C905 

was causing issues for me, From my limited knowledge the \ I was thinking should have been / 

python3 tools/keymsg-decrypt.py EncryptionKeyMessage_001F2904C905.bin 001F2904C905 and it worked so was able to finish the installation on the Pi

I have built a cantenna on a 90cm dish but unfortunately my signal is not locking. Will post a picture of my sdrsharp today to see what the issues are as the frequency is slightly off at 1692170 ? if I use my other sdr its then at 1692100. also i should add my dish will hold a signal when I turn the dish 2-5 degrees in any direction( left, right, up & down) which leads me to scratch my head as when I play with ku band lnb setups if I'm off my 1 degree I completely lose my signals 

Have some free time today will try for a lock and send a picture or two of the waterfall.

Thank you for the hard work, effort & tutorials you have provided

**Comment by adamg261** [comment]
Hi Sam

Here is a 2 snap shots of my laptop running sdrsharp. I have ( silly me) figured why frequency was wrong, Was me lol ppm correction was off I think.

Appreciate your time
![Screenshot 2020-12-01 112750](https://user-images.githubusercontent.com/75062627/100688638-8dc96e00-33ce-11eb-9519-973f8c171641.png)
![Screenshot 2020-12-01 113340](https://user-images.githubusercontent.com/75062627/100688655-94f07c00-33ce-11eb-9d5d-b93e6f827303.png)

**Comment by adamg261** [comment]
Hi Sam

I have pickup a suggested wifi antenna from 

http://www.citytechnology.com.au/store/19dbi-2.4ghz-square-grid-dish-antenna#!prettyPhoto

Put it together and made the modification as suggested. Still no luck with a lock :( . I've noticed that even with this antenna i can move up/down/left&right about 10 degrees and still see a signal was wondering if you have any clues to what might be going on?

I was at max getting in sdrsharp a snr of 11 with the 90cm offset with cantenna now with the wifi antenna im seeing 13/14 snr.

Any guidance is greatly appreciated mate.

Adam

**Comment by sam210723** [comment]
Hi Adam,
Apologies for not replying sooner.

Your signal in SDRSharp looks good! Have you been using [goesrecv-monitor](https://github.com/sam210723/goesrecv-monitor) when trying to get goesrecv to lock? Could you also copy your goesrecv.conf file into a comment here for me to double check?

> I should add my dish will hold a signal when I turn the dish 2-5 degrees in any direction( left, right, up & down) which leads me to scratch my head as when I play with ku band lnb setups if I'm off my 1 degree I completely lose my signals

Good eye! This is because the beam-width of a dish becomes narrower as frequency increases, assuming the dish diameter is the same. For example, the -3 dB beam-width of a 1m dish at L-band is about 12°, but at Ku-band it's about 1.7°.

> From my limited knowledge the \ I was thinking should have been /

Yes Windows prefers backslash in file paths but will tolerate forward slash. I've updated that line in the setup guide to use a forward slash. Thanks for pointing that out.

**Comment by adamg261** [comment]
Hi Sam

thank you for the help mate. 

Here is a cut and past of the goesrecv.conf


[demodulator]
satellite = "GK-2A"
downlink = "lrit"
source = "rtlsdr"

# [airspy]
# frequency = 1692140000
## 2500000 for the R2, 3000000 for the Mini
# sample_rate = 3000000
# gain = 18
# bias_tee = true

[rtlsdr]
frequency = 1692140000
# sample_rate = 1024000
# gain = 30
# bias_tee = true
# device_index 


[costas]
max_deviation = 200e3

[decoder.packet_publisher]
bind = "tcp://127.0.0.1:5004"
send_buffer = 1048576

[monitor]
statsd_address = "udp4://localhost:8125"

[clock_recovery.sample_publisher]
bind = "tcp://0.0.0.0:5002"
send_buffer = 2097152

[demodulator.stats_publisher]
bind = "tcp://0.0.0.0:6001"

[decoder.stats_publisher]
bind = "tcp://0.0.0.0:6002"



I have the goesrecv monitor running also on laptop but through movements I see no change in the "eye " or Verb.

thank you for the information on bean-width great to learn something new

Cheers

Adam

**Comment by adamg261** [comment]
I don't know why in last post its changes the font size of the information in the config file  all i did was cut and paste it, in the file its all the same size font , no bold, no underlines?

Lol could this be the issue

**Comment by adamg261** [comment]
Hi Sam

Sorry for multiple posts

another cut and paste 

[demodulator]
satellite = "GK-2A"
downlink = "lrit"
source = "rtlsdr"

# [airspy]
# frequency = 1692140000
## 2500000 for the R2, 3000000 for the Mini
# sample_rate = 3000000
# gain = 18
# bias_tee = true

[rtlsdr]
frequency = 1692140000
# sample_rate = 1024000
# gain = 30
# bias_tee = true
# device_index 


[costas]
max_deviation = 200e3

[decoder.packet_publisher]
bind = "tcp://127.0.0.1:5004"
send_buffer = 1048576

[monitor]
statsd_address = "udp4://localhost:8125"

[clock_recovery.sample_publisher]
bind = "tcp://0.0.0.0:5002"
send_buffer = 2097152

[demodulator.stats_publisher]
bind = "tcp://0.0.0.0:6001"

[decoder.stats_publisher]
bind = "tcp://0.0.0.0:6002"

**Comment by sam210723** [comment]
Ah that would be the GitHub markdown formatting. "#" is used to create a heading line. I've edited your comment to make it a code block so it ignores formatting characters.

Your config file looks fine, one thing I would try however is to remove the "# " from ``# gain = 30``. The automatic gain in the RTL-SDR may be misbehaving, so forcing it to a higher gain may help. Restart goesrecv after doing that and see if it locks.

**Comment by adamg261** [comment]
Ok Sam

Thank you will try that this afternoon.  Appreciate the help mate

Cheers

**Comment by adamg261** [comment]
Hey Sam

One more question if you dont mind, Am going to set it up all outside this afternoon and go for a lock. 
If i adjust a setting in the goesrecv.conf do i have to reset the Pi or can i just " Ctrl C " the  " goesrecv -v -i 1 -c goesrecv.conf " and restart it - Or is it capable of seeing the changes I make on the fly with editing the goesrecv.conf be seen straight away by the program when i edit it with WinSCP and save ?

Thanks again mate, will update you with the results.

**Comment by sam210723** [comment]
You'll need to stop goesrecv with Ctrl + C then run the command again. No need to reset the whole Pi.

**Comment by adamg261** [comment]
Hi Sam

Unfortunately I’m going to have to get back to you next week mate. My
nooelec Lna just died :/ lol .. I also have the goes Lna arriving hopefully
during the week and extended tuning sdr. Will update you.

Mate thank you for the help and great software you have provided everyone
what a great effort and abilities you have 👍👍🙏👍👍

Cheers

Adam, North Qld

**Comment by adamg261** [comment]
Hi Sam

I have setup the dish again without success, I removed the "#" from gain but have noticed I'm having to remove the "#" from bias_tee for it to turn on the lna (I didn't have to do this before). I appreciate your help but I'm scratching my head as to what's going on as I have also set it up with sdrsharp and see a good signal.  One thing I'm using a standard nooelec lna not the Goes sawbird would this be part of my problem?

I will try again tomorrow .. unfortunately  I'm dealing with a bad summer here in Cairns the U.v is every high and can only work outside in the early evening so time is limited for me.

**Comment by adamg261** [comment]
Hey Sam

not luck :( . something weird is going on still with gain but have attached pictures with the gain settings from config file in the background. I also thought maybe(silly I know- wrong satellite) and have included a snapshot of hrit GK-2a and another of lrpt GK-2a.  through SDR# on my laptop I get a great snr.

I have tried 2 different sdr's and have used 1. different usb cables 2. different length usb 3.power injector 2 way usb cable  4. direct to Pi (no usb leads) 5. a new sd card and whole new install of your great software. 6. sma patch lead from first lna to the second lna incase of them been hooked together in series was an issue.

I had just for fun also compiled the Goes Raspberry beforehand and put that sd card into the Pi and changed the settings in the config file to yours and besides the "HRIT", "GOES" up the top the first line which came in showed 2 packets then were all errors after the first line.  I'm hoping this helps in someway as to maybe what's going on because as of now I'm at a loss as my abilities are subpar. hope I haven't rambled or provided to much to read.

my setup is

1. RTL-SDR Blog v3 , Generic RTL-SDR .
2. 2x Nooelec Lana's
3.  City Technology (AU) Wifi antenna (modifications made)
4. Raspberry Pi 3b+ 32gb running Raspberry Pi OS ( Port of Debian desktop )
5. Putty & winscp for communications to desktop

Thank you for reading and helping a noob 

Adam

![Screenshot 2020-12-16 154000](https://user-images.githubusercontent.com/75062627/102312925-56a4b080-3fbb-11eb-83fa-3323ac5e6e1b.png)
![Screenshot 2020-12-16 154355](https://user-images.githubusercontent.com/75062627/102312938-5c9a9180-3fbb-11eb-8d96-1c81e617f433.png)
![Screenshot 2020-12-16 154618](https://user-images.githubusercontent.com/75062627/102312947-60c6af00-3fbb-11eb-92c0-7b11aad4701d.png)
![Screenshot 2020-12-16 154938](https://user-images.githubusercontent.com/75062627/102312950-615f4580-3fbb-11eb-8510-f4fe58bef8f8.png)
![Screenshot 2020-12-16 155207](https://user-images.githubusercontent.com/75062627/102312952-62907280-3fbb-11eb-8cbc-697c86fad457.png)

**Comment by sam210723** [comment]
Hi Adam, this is very strange. Are you able to record some IQ in SDRSharp and sent it to me via [WeTransfer](https://wetransfer.com/)? I can then try demodulate it here to confirm your SNR is sufficient. From the screenshots it looks ok.

**Comment by adamg261** [comment]
Ok Sam

Will do that now mate, give me 15

**Comment by adamg261** [comment]
Hey Sam

Can I have your email to send the link for wetransfer mate ?

Cheers

**Comment by sam210723** [comment]
sam@vksdr.com

**Comment by adamg261** [comment]
Ok

Transferring now mate 👍

**Comment by sam210723** [comment]
Thanks, I'll check it out when I'm home later tonight.

**Comment by adamg261** [comment]
👍

**Comment by sam210723** [comment]
Hi Adam,

When you play your recording back in SDRSharp do you see something like this? I can see a large DC spike in the center of the spectrum when playing the recording here. Otherwise the SNR looks good.
![image](https://user-images.githubusercontent.com/5117093/102345736-8f5b7e80-3fe9-11eb-9c6c-b72477a3a294.png)

The test demodulator I have in GNU Radio was unable to lock on this recording at first.
![image](https://user-images.githubusercontent.com/5117093/102345376-0a706500-3fe9-11eb-847e-46cc55e0f254.png)

I then added a DC blocker inside the demodulator and now the signal is locking fine.
![image](https://user-images.githubusercontent.com/5117093/102345601-5fac7680-3fe9-11eb-8e54-00421f8c74ba.png)

I quickly connected it all to xrit-rx and it is decoding the signal correctly, so no issues with your RF setup! This looks to be a software or configuration issue.
![image](https://user-images.githubusercontent.com/5117093/102347496-34775680-3fec-11eb-8088-ee3e6faca62d.png)


Something else you could try is to changing the sample rate in the `goesrecv.conf` file.
Under the `[rtlsdr]` section try changing `sample_rate = 1024000` to `sample_rate = 900000`.
If that does not work try adding a `#` before `sample_rate` so goesrecv can automatically pick a sample rate.

**Comment by adamg261** [comment]
Hi Sam

Its great to know the Rf side is mostly right. No I don't see a spike in the middle on the recording but I will setup live when home this morning as work an early shift, will be home at 10am Qld time and will try with a sample rate of 900000 in sdr# first. 

I have had the (#) before sample_rate and also with out I have tried the 1024000 and also 2400000 but not ever your suggested 900000. Just for reference and to try and learn about this why would I not  been seeing the DC spike ? For a while I was thinking maybe I was on fengyun 2f ( very close) but for the life of me couldn't find the freq for it to clarify.

Thank you for the efforts in helping and teaching me Sam, Talk soon when home

**Comment by adamg261** [comment]
ok update, I have sdr# at work and downloaded the wetransfer file and If i take the tick out of (Correct IQ) I get a big spike. hope this helps in some way. If listening to the Raw file and take the tick  correct IQ in sdr# I can hear a data stream with it unticked I hear just Noise - garbage.

At lest now I see this

Adam

**Comment by adamg261** [comment]
Hi Sam

Have update the suggested line and unfortunately no success. I tried sample_rate = 900000 but wouldn't accept it , so I used sample_rate = 900001 which didn't produce an error but still no packets mate. funny thing I've noticed with SDR# is when live rtl-sdr usb I get no DC spike ( With correct IQ on or off ), If I record it and play it back the spike is there with correct IQ off ?

I have uploaded another raw file to wetransfer if your interested. I have TeamViewer on my laptop if you would like access and have some time to help further or are keen to know what's at the heart of this issue. Also Is there a compiled raspberry Pi 3 image with your software at hand that I  could try ( was something I thought of to rule out my user error )  I have this morning tried 
1. a battery pack power supply for Pi
2.  a different power pack for Pi
3.  Supplied direct power to lna with DC Block ( Incase Pi wasn't powering it correctly )
4.  sample_rate = 900000 which gave an error and exited 
5.  sample_rate = 900001 which worked but still had no packets 
6.  gain or # gain to get manual gain I need to be from 6-19, If I input 5 the gain is automatic and with each line moves up in values. If I let it climb to max gain still no packets of data or lock 
Cheers 

Adam

**Comment by adamg261** [comment]
Hey Sam

I had another thought ( learning still ) . would it be worth putting Ubuntu on a laptop and compiling the software again to rule out the hardware of the Pi? I have twice installed Raspberry OS, Or is there a better Pi OS to install ?

I see lots of people getting your great work setup correctly and want to succeed. I know as a developer your time should be on time off and making your software better all the time and am so happy with the time and information you have given me mate

**Comment by adamg261** [comment]
Just an update mate

I have installed Ubuntu on my old laptop and installed all Goestools and Xrit-rx  with the same results. Its not the Pi. I installed sdr# on it also and for some reason the signal is very very weak. If I plug up my windows laptop it shows a great strong signal with a SNR of 14-15. On Ubuntu wouldn't be getting a SNR of 5-6 ( have adjusted gain and also tried manual gain with no success. I will this afternoon try when back home another sdr but the sdr I'm using atm is the sdr-blog v3 which as far as I'm aware is better at 1.692.140 mhz. 

any suggestions or thoughts on this are welcome and appreciated 

Cheers

Adam

**Comment by sam210723** [comment]
Hi Adam,

Lets lock the sample rate at `1024000` and gain to `25` in `goesrecv.conf` just to reduce the number of variables we're working with. So far we know the RF hardware is OK and the signal is strong enough but goesrecv never locks. The downlink frequency seems to be spot on based on your IQ recordings, so that's unlikely to be the issue.

Many people are using the RTL-SDR v3 dongle for L-band stuff so that's fine. Just double checking you've been compiling `librtlsdr` yourself as per the guide? The bias-tee on the v3 will not work unless this particular version of the library is used.

![librtlsdr](https://user-images.githubusercontent.com/5117093/102679268-30208880-41fa-11eb-9c74-41d06ca15e77.png)

**Comment by sam210723** [comment]
I've just noticed the PLL warning in your goesrecv screenshots (`[R82XX] PLL not locked!`). This is likely to cause an issue where goesrecv cannot tune the SDR to the LRIT frequency. I also noticed you have the `frequency` parameter under `[airspy]` uncommented, I've seen this cause issues when not using the Airspy mode.

I have prepared a `goesrecv.conf` file below which is setup for a RTL-SDR. Try replacing your `goesrecv.conf` file with the one below then running goesrecv again.

```
[demodulator]
satellite = "GK-2A"
downlink = "lrit"
source = "rtlsdr"

[airspy]
# frequency = 1692140000
## 2500000 for the R2, 3000000 for the Mini
# sample_rate = 3000000
# gain = 18
# bias_tee = false

# [rtlsdr]
frequency = 1692140000
sample_rate = 1024000
gain = 30
# bias_tee = false
# device_index = 0

# [nanomsg]
# sample_rate = 2400000
# connect = "tcp://1.2.3.4:5005"
# receive_buffer = 2097152

[costas]
max_deviation = 200e3

[clock_recovery.sample_publisher]
bind = "tcp://0.0.0.0:5002"
send_buffer = 2097152

[quantization.soft_bit_publisher]
bind = "tcp://0.0.0.0:5001"
send_buffer = 1048576

[decoder.packet_publisher]
bind = "tcp://0.0.0.0:5004"
send_buffer = 1048576

## Demodulator JSON statistics output (gain, frequency correction)
[demodulator.stats_publisher]
bind = "tcp://0.0.0.0:6001"

## Decoder JSON statistics output (Viterbi, RS)
[decoder.stats_publisher]
bind = "tcp://0.0.0.0:6002"

## Aggregated statistics output (counters, gauges, and histograms)
[monitor]
statsd_address = "udp4://localhost:8125"
```

**Comment by adamg261** [comment]
Great, thanks!

Will try when home in and hour mate

thank you

**Comment by adamg261** [comment]
> Hi Adam,
> 
> Lets lock the sample rate at `1024000` and gain to `25` in `goesrecv.conf` just to reduce the number of variables we're working with. So far we know the RF hardware is OK and the signal is strong enough but goesrecv never locks. The downlink frequency seems to be spot on based on your IQ recordings, so that's unlikely to be the issue.
> 
> Many people are using the RTL-SDR v3 dongle for L-band stuff so that's fine. Just double checking you've been compiling `librtlsdr` yourself as per the guide? The bias-tee on the v3 will not work unless this particular version of the library is used.
> 
> ![librtlsdr](https://user-images.githubusercontent.com/5117093/102679268-30208880-41fa-11eb-9c74-41d06ca15e77.png)

Sam

I have just followed the guide to to the extent of copying and pasting mate. librtlsdr I just followed the instructions and copied them ( noob)  sorry have I missed something ?

I have tried again with the config and no ppl lock :(

**Comment by adamg261** [comment]
The Bias-tee turns on though I need to uncomment it (#bias-tee = true) wont work I have to (bias-tee = true)

also in the config information you sent I had to uncomment  ( # [rtlsdr] )  to ( [rtlsdr] )

merry Christmas mate

**Comment by sam210723** [comment]
Ah yes, good spot! Did you also comment `[airspy]` when you made that change?

Here's an updated config file for you to try:
```
[demodulator]
satellite = "GK-2A"
downlink = "lrit"
source = "rtlsdr"

# [airspy]
# frequency = 1692140000
## 2500000 for the R2, 3000000 for the Mini
# sample_rate = 3000000
# gain = 18
# bias_tee = false

[rtlsdr]
frequency = 1692140000
sample_rate = 1024000
gain = 30
bias_tee = true
# device_index = 0

# [nanomsg]
# sample_rate = 2400000
# connect = "tcp://1.2.3.4:5005"
# receive_buffer = 2097152

[costas]
max_deviation = 200e3

[clock_recovery.sample_publisher]
bind = "tcp://0.0.0.0:5002"
send_buffer = 2097152

[quantization.soft_bit_publisher]
bind = "tcp://0.0.0.0:5001"
send_buffer = 1048576

[decoder.packet_publisher]
bind = "tcp://0.0.0.0:5004"
send_buffer = 1048576

## Demodulator JSON statistics output (gain, frequency correction)
[demodulator.stats_publisher]
bind = "tcp://0.0.0.0:6001"

## Decoder JSON statistics output (Viterbi, RS)
[decoder.stats_publisher]
bind = "tcp://0.0.0.0:6002"

## Aggregated statistics output (counters, gauges, and histograms)
[monitor]
statsd_address = "udp4://localhost:8125"
```

**Comment by adamg261** [comment]
Heya mate

I’m sure I did. Will let you Know in the morning if that’s ok out with the
family 👍 I’m persistent lol .. will get to the bottom of it and hopefully
give you something back to help others if this appears in the future on
GitHub

👍 legend

Adam

**Comment by sam210723** [comment]
No worries! I'll let you know if I think of anything else to try.
I'll leave this issue open here so you can keep me updated.

All the best.
Sam.

**Comment by adamg261** [comment]
Awesome, thanks!

**Comment by adamg261** [comment]
unfortunately still no lock (Pll not locked also)

I will update you in an hour mate as have Joes software which I intend to
use with Noaa, Meteor, Metop but have gk-2a option and will send
information through on any issues or problems

My main aim is xrit-rx on the Pi ( easy great code )   and joes software
with my Sarctrac rotator with my 2nd wifi modded for 1.7ghz -  for the
other stuff  (Geo orbit ) with my laptop and airspy mini which ill have
access to on monday/tuesday .
My qhf is all working well for apt so these are the other goals   screen
grabs below from first attempt with your config

**Comment by adamg261** [comment]
Sorry Sam

I tried 30 as gain first then 5 through to 14 with ctrl c stop and start
every time

**Comment by adamg261** [comment]
Sam

I have some interesting information. Joes Software wouldn't work - At first , Though now I see an issue which looks like could be the reason why Pi not working !

Ok so I have attached screen shots of the outcome. I'm using spyserver and was able to run sdr# at the same time and at first i had no signal on 1,692.140 .. I've had this issue before, If I after booting change the freq to 1,492.140 and then back to 1,692.140 I then see a good signal ! ... personally I don't understand why. then If I run Joes software I get a lock ! . If I unlpg the sdr and close all software and dont run sdr# first joes software wont lock ! . if I stop the software and do the above steps changing freq in sdr# start joes software it works .  I will attach screen grabs sorry if to many Sam -  My question is can we port spyserver to goestools ? or can we have it change freq to test this theory I have ?   Maybe its just my sdr but I have also used my other sdr which i will point out hasn't got the thermal protection as the sdr-blog v3 has.  Hope in someway this helps or just proves I have a half faulty sdr which needs a push. either way I hope still to have your software for my Pi running Xrit-rx as this is the one I want for gk-2a and not the laptop. 

![Screenshot 2020-12-20 083906](https://user-images.githubusercontent.com/75062627/102701490-40407280-42a3-11eb-81e3-89b4df275050.png)
![Screenshot 2020-12-20 083957](https://user-images.githubusercontent.com/75062627/102701492-42a2cc80-42a3-11eb-962d-e8d177312189.png)
![Screenshot 2020-12-20 084842](https://user-images.githubusercontent.com/75062627/102701493-43d3f980-42a3-11eb-95c2-95d67d34a07a.png)
![Screenshot 2020-12-20 084406](https://user-images.githubusercontent.com/75062627/102701502-564e3300-42a3-11eb-8acc-6260b63a8346.png)
![Screenshot 2020-12-20 084842](https://user-images.githubusercontent.com/75062627/102701503-5817f680-42a3-11eb-8b97-d04a851af8d8.png)

Sam, I hope this all helps and look forward to a reply .   I had ordered a nooelec e400 extended range and sawbird last month and have an airspy Mini here Monday Tuesday so this can be closed if you like .   Or I would be happy to take steps to see if can be resolved if you want to dig deeper. I hope In someway this may have helped someone who might have come across the same problems - But ( noob here ) Could be all along what you had thought simply regarding config. Though I have tried the other config you sent and still no packets mate

cheers

Adam

**Comment by sam210723** [comment]
Hi Adam,

That's very strange. I can't say I've seen this issue before. I'm happy to leave this open until you have a working setup either with a new SDR or your current one.

I have run out of ideas for this one unfortunately. Let me know if you try it out with your Airspy Mini when it arrives.
I'll let you know if I come up with anything else to try for the RTL-SDR.

Sam.

**Comment by adamg261** [comment]
Hey Sam

Thanks for getting back to me and also all the help.

I thought it’s strange also. Though I have a couple ideas to test settings
in spysever and if see signal without having to change frequency in sdr#
first -  transfer them to the goestools config see if it works.

Will get back to you and let you know the outcome regarding Airspy mini and
also the nooelec extended range when it arrives. I will within the week let
you know how I go with the Airspy mini. Have a fair bit on next few days as
had family arrive.

Have a great Christmas mate and merry Christmas

Cheers

Adam

**Comment by adamg261** [comment]
![Screenshot 2020-12-23 143254](https://user-images.githubusercontent.com/75062627/102959895-7e9c9280-452c-11eb-9a94-aa631803f3e8.png)

Will update you soon with more results mate. Airspy mini working right away.  loving the program and webpage interface ! will update this before  I close it with any findings for the rtl-sdr blog v3 . personally I think its faulty - ish

Adam

**Comment by adamg261** [comment]
Hi Sam

Ok I have a outcome that might help others. I got a Nooelec Sdr extended tuner for Christmas. Plugged it up and changed the config to your guide and straight away it worked like the airspy mini. good lock and working well.

I personally think i had a half faulty rtl-sdr blog. to confirm this if people have this problem follow these steps.

1. run spysever on Pi or install sdr sharp on Pi 
2.  If when you open sdr sharp and go directly to 1.692.140
3. If when you go this frequency you see no signal follow below step
4.  tune down to 1.492.140 and then back up to 1.692.140
5.  you should now see a signal through sdr sharp and shows you will not be able to use this sdr or similar if you have had issues setting up Xrit-rx you need to use/try another dongle.

I don't know why I'm not smart enough to answer that but from what I've learnt from Sam and taught myself I personally think the rtl-sdr blog v3 may work for this but mine I feel was having issues this high in the spectrum and needed a kick in the bum to work just in sdr sharp on linux/Pi. this maybe a linux issue only though as I have not seen this issue in windows when tuning to the frequency straight away.  I hope this helps someone who faces this issue at some point

**Comment by sam210723** [comment]
Hi Adam,

This sure is a strange one. I know of many people using the RTL-SDR Blog v3 dongle for GK-2A and I had not heard this one before. I'm glad your setup is working now!

I'll close this issue for now. Enjoy the images!
